### PR TITLE
Clueless pinyinfix

### PR DESCRIPTION
**Pull request by theClueless**
fix the pinyin issue jjw24#111
probably best to merge only after we are finished with the current changes.

### CODE REVIEW

**Comment by jjw24** [comment]
hey @theClueless this pr works, though it essentially just does another run of fuzzy search if nothing is found in the initial run.  I think there is a better way of doing this without having to do another run for every search where allQuerySubstringsMatched is false. It really just needs to check if shouldusepinyin is on and string contains Chinese, then convert either query string or string to compare that contains Chinese to pinyin and run fuzzy search as per normal.

I will do this in a separate request for now.

**Comment by theClueless** [comment]
The old code use to do exactly that.
And I think that if you find Chinese (pinyin style), you still also need to check the normal string for the English version.
For example in the original issue, he typed ditu but ditu can mean pinyin or it can mean I'm searching for the program ditur.exe (just making something up) but my point is that you should try both.

**Comment by jjw24** [comment]
Yeah i meant including the old code was not efficient. What happens is it just converts Chinese into pinyin (alphabet) so it can do character matching. The root cause was the fact that the string to compare was Chinese and there was no conversion of the string to compare from Chinese to Pinyin, that's why nothing came back. Additionally the current code is not efficient as it does two runs of fuzzy search where we really just need to figure out if either string is Chinese characters then convert then do fuzzy search.

**Comment by jjw24** [comment]
Which also leads me to think maybe we can support other languages search additional to just Chinese as long as the convert is written to convert the language to the same alphabet/characters. I will add this in

**Comment by jjw24** [comment]
> The old code use to do exactly that.
> And I think that if you find Chinese (pinyin style), you still also need to check the normal string for the English version.
> For example in the original issue, he typed ditu but ditu can mean pinyin or it can mean I'm searching for the program ditur.exe (just making something up) but my point is that you should try both.

Yeah agree, will keep in mind. I think I can also pull pinyin calc method out of fuzzy search. Didn't realise it just does the conversion then call fuzzy again. Working on a pr will push sometime soon.

**Comment by theClueless** [comment]
> Yeah i meant including the old code was not efficient. What happens is it just converts Chinese into pinyin (alphabet)


to my understanding this is not what it is doing.
It take normal English and English chars are converted into Chinese. like shown in the issue:
user types: "ditu" 
so the code need to search "ditu" (for normal English) and addition to that also "地图".
so the current code is efficient since it does what it needs to, right?
I'm not sure how you could do that differently.

**Comment by theClueless** [comment]
fixed by other PR

**Comment by jjw24** [comment]
#131

**Pull request closed without merging**
