### PR TITLE
Auto update improvements: Updater

### PR DESCRIPTION
**Pull request by theClueless**
started working on updating the updater (changing from static to instance) and moving the repository to app.config so it would be configurable and later on we can start releasing with auto updates enabled

### CODE REVIEW

**Comment by jjw24** [comment]
Not sure how we can solve the portable mode's UserData. Had a brief look at squirrel project, didn't see anything obvious to exclude folder during installation

**Comment by theClueless** [comment]
we can always backup the data to another folder before the update and afterwards get it back or something like that, or just don't give this ability in portable mode

**Comment by theClueless** [comment]
but auto updates if we do changes is really important

**Comment by jjw24** [comment]
Yeah that was the last resort for me that I can think of, might just move the folder out temporarily but pretty ugly. I was alternatively also wondering if we could switch from squirrel to something else. So far just a thought. But yeah continue with the work on auto updates.

**Review by jjw24 — APPROVED** [review]

**Pull request merged**
